sonar.projectKey=karlosarr_pokedexapp
sonar.organization=karlosarr

# Exclude CFamily languages to prevent SonarQube build-wrapper requirement errors in Flutter
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

# Optional: exclude generated directories from analysis altogether
sonar.exclusions=ios/**,android/**,macos/**,windows/**,linux/**,web/**,build/**,.dart_tool/**
