sonar.projectKey=karlosarr_pokedexapp
sonar.organization=karlosarr

# Configure source directories
sonar.sources=lib
sonar.tests=test

# Exclude CFamily languages to prevent SonarQube build-wrapper requirement errors in Flutter
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

# Set code coverage report path for Dart/Flutter
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclude generated and platform directories from analysis altogether
sonar.exclusions=ios/**,android/**,macos/**,windows/**,linux/**,web/**,build/**,.dart_tool/**,.github/**,lib/core/network/**,lib/core/theme/**
